In [2]:
import pandas as pd
import numpy as np

def readin(filepath):
    df = pd.read_csv(filepath, header=None)
    df.drop([0], axis=1, inplace=True)
    return df

filepath_weights = "./data/a/a_w.csv"
filepath_biases = "./data/a/a_b.csv"
weights = readin(filepath_weights)
biases = readin(filepath_biases)

In [3]:
weights

1         2         3         4         5
0   0.770941  0.239120  0.178334  0.020453  0.902570
1   0.162568  0.552057  0.260752  0.204093  0.430102
2   0.310077  0.720633  0.191936  0.781703  0.714269
3   0.717529  0.957819  0.155335  0.766732  0.091014
4   0.301734  0.922675  0.273463  0.193470  0.822733
5   0.260493  0.716749  0.990273  0.464001  0.801016
6   0.356400  0.288340  0.892149  0.111554  0.021687
7   0.419026  0.974364  0.128274  0.577329  0.118821
8   0.726411  0.541172  0.960503  0.577023  0.035408
9   0.429903  0.574102  0.245389  0.545223  0.641441
10  0.790693  0.480211  0.870675  0.709645  0.075890
11  0.091553  0.393053  0.687032  0.015916  0.438904
12  0.423793  0.551500  0.476965  0.519232  0.295090
13  0.154773  0.814489  0.570184  0.438847  0.207582
14  0.678918  0.492827  0.547304  0.990029  0.937703

In [4]:
biases

1         2         3         4         5
0  0.985023  0.660864  0.640285  0.802458  0.897461
1  0.184054  0.097129  0.439557  0.692748  0.565846
2  0.092926  0.067644  0.257744  0.341688  0.214793

In [5]:
m_layers = len(biases)
n_nodes = len(biases.columns)
w = []
b = []

In [6]:
for i in range(m_layers):
    w.append(weights[i*n_nodes:(i+1)*n_nodes].T.values)
    b.append(biases[i:i+1].values.squeeze())
    

In [7]:
w

[array([[0.77094086, 0.16256778, 0.31007699, 0.71752937, 0.30173373],
        [0.23911989, 0.55205656, 0.72063287, 0.95781883, 0.92267465],
        [0.17833366, 0.26075201, 0.19193596, 0.15533461, 0.27346263],
        [0.02045298, 0.20409294, 0.781703  , 0.76673205, 0.19347049],
        [0.90257019, 0.43010179, 0.71426882, 0.09101359, 0.82273306]]),
 array([[0.26049323, 0.35639996, 0.41902647, 0.72641085, 0.42990326],
        [0.71674856, 0.2883403 , 0.97436406, 0.54117203, 0.57410244],
        [0.99027268, 0.89214873, 0.12827391, 0.96050294, 0.24538913],
        [0.46400075, 0.11155372, 0.5773295 , 0.57702335, 0.54522313],
        [0.80101617, 0.02168702, 0.11882143, 0.03540801, 0.6414406 ]]),
 array([[0.79069312, 0.09155339, 0.42379296, 0.15477327, 0.67891789],
        [0.48021084, 0.39305289, 0.55149982, 0.81448891, 0.49282672],
        [0.87067538, 0.6870319 , 0.47696471, 0.5701844 , 0.54730409],
        [0.70964516, 0.01591644, 0.51923228, 0.43884731, 0.99002919],
        [0.07589

In [8]:
b

[array([0.9850227 , 0.66086395, 0.64028464, 0.80245799, 0.89746142]),
 array([0.18405393, 0.09712902, 0.4395569 , 0.69274761, 0.56584571]),
 array([0.09292619, 0.06764403, 0.25774405, 0.34168816, 0.21479282])]

In [14]:
b_new = b[0]
w_new = w[0]
for i in range(1, m_layers):
    print(i)
    b_new = np.dot(w[i], b_new) + b[i]
    w_new = np.dot(w[i], w_new)
print(b_new)
print(w_new)

1
2
[4.93034911 6.77602221 7.72818905 6.48431587 4.84497893]
[[2.23503771 1.44783218 2.66709692 2.69578138 2.29100668]
 [2.98198231 1.96713634 3.577374   3.59433718 3.05224976]
 [3.40154892 2.28891201 4.12175934 4.08685069 3.53405071]
 [2.85364089 1.74355286 3.20835308 3.22430284 2.78663634]
 [2.35855058 1.29346973 2.26401728 2.26828789 2.09150597]]


In [10]:
def linear_forward(A, W, b):
    return np.dot(W, A) + b

def model_forward(X, weights, biases, m_layers):
    """
    Forward propagation for a fully-connected model"""
    A = X
    
    for l in range(m_layers):
        A = linear_forward(A, weights[l], biases[l])
    return A

In [11]:
X_test1 = np.array([0,0,0,0,1]) 
model_forward(X_test1, w, b, 3)

array([ 7.22135579,  9.82827197, 11.26223977,  9.27095221,  6.9364849 ])

In [13]:
y_new1 = model_forward(X_test1, w_new, [b_new], 1)
y_new1

array([ 7.22135579,  9.06702889, 10.01919573,  8.77532255,  7.13598561])