In [10]:
import pandas as pd
import numpy as np

def readin(filepath):
    df = pd.read_csv(filepath, header=None)
    df.drop([0], axis=1, inplace=True)
    return df

filepath_weights = "./data/b/b_w.csv"
filepath_biases = "./data/b/b_b.csv"
weights = readin(filepath_weights)
biases = readin(filepath_biases)

In [11]:
# weights
# biases

In [12]:
m_layers = len(biases)
n_nodes = len(biases.columns)
w = []
b = []

In [13]:
for i in range(m_layers):
    w.append(weights[i*n_nodes:(i+1)*n_nodes].T.values)
    b.append(biases[i:i+1].values.squeeze())    

In [14]:
b_new = b[0]
w_new = w[0]
for i in range(1, m_layers):
    b_new = np.dot(w[i], b_new) + b[i]
    w_new = np.dot(w[i], w_new)
print(b_new)
print(w_new)

[4.20869717 5.72944864 4.38338539 3.22271122 2.85044733]
[[3.40024138 2.48222301 3.01782662 2.93995725 2.33681416]
 [5.34668342 4.0322299  4.6081539  4.73197673 3.25019999]
 [3.55671673 2.64465123 3.07145874 3.13733109 2.06166728]
 [2.70747384 2.03870195 2.331609   2.39768473 1.64790235]
 [2.17160681 1.71029264 1.83313118 1.96613715 1.32862212]]


In [15]:
def linear_forward(A, W, b):
    return np.dot(W, A) + b

def model_forward(X, weights, biases, m_layers):
    """
    Forward propagation for a fully-connected model"""
    A = X
    for l in range(m_layers):
        A_prev = A
        A = linear_forward(A_prev, weights[l], biases[l])
    return A

In [16]:
X_test1 = np.array([0,0,0,0,1]) 
model_forward(X_test1, w, b, 3)

array([6.54551133, 8.97964863, 6.44505267, 4.87061357, 4.17906945])

In [17]:
model_forward(X_test1, np.array([w_new]), np.array([b_new]), 1)

array([6.54551133, 8.97964863, 6.44505267, 4.87061357, 4.17906945])

In [9]:
out = np.matmul(w[2], np.matmul(w[1], np.matmul(w[0], X_test1) + b[0])+b[1])+b[2]
out1 = np.matmul(w_new, X_test1) + b_new
print(out,"\n",out1)

[ 7.22135579  9.82827197 11.26223977  9.27095221  6.9364849 ] 
 [ 7.22135579  9.82827197 11.26223977  9.27095221  6.9364849 ]
